/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: a51c307dcc6d015726004544f5ff7bd9)
interface __BaseEnv_CloudflareEnv {
	CURIO_SOURCE_MEDIA: R2Bucket;
	CURIO_DB: D1Database;
	CURIO_PROCESSING_QUEUE: Queue;
	BROWSER: BrowserRun;
	ASSETS: Fetcher;
	OPENAI_RETRIEVAL_MODEL: "gpt-5.4-mini";
	ENABLE_EXPERIMENTAL_INSTAGRAM_EMBED: "true";
	OPENAI_API_KEY: string;
	OPENAI_TRANSCRIPTION_MODEL: string;
	OPENAI_ANALYSIS_MODEL: string;
	SUPABASE_URL: string;
	SUPABASE_SECRET_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	CURIO_API_TOKEN: string;
	CURIO_ALLOWED_ORIGINS: string;
	SUPABASE_AUTH_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	CURIO_INVITED_EMAILS: string;
	CURIO_LEGACY_OWNER_EMAIL: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./worker-entry").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker-entry");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_RETRIEVAL_MODEL" | "ENABLE_EXPERIMENTAL_INSTAGRAM_EMBED" | "OPENAI_API_KEY" | "OPENAI_TRANSCRIPTION_MODEL" | "OPENAI_ANALYSIS_MODEL" | "SUPABASE_URL" | "SUPABASE_SECRET_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "CURIO_API_TOKEN" | "CURIO_ALLOWED_ORIGINS" | "SUPABASE_AUTH_URL" | "SUPABASE_PUBLISHABLE_KEY" | "CURIO_INVITED_EMAILS" | "CURIO_LEGACY_OWNER_EMAIL">> {}
}
