// @ts-expect-error Generated by OpenNext before deployment.
import openNextWorker from "./.open-next/worker.js";
import { consumeProcessingQueue } from "./lib/jobs/processor";
import type { ProcessingJobMessage } from "./lib/jobs/domain";

// @ts-expect-error Generated by OpenNext before deployment.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

export default {
  fetch(request, env, context) {
    return openNextWorker.fetch(request, env, context);
  },
  queue(batch, env) {
    return consumeProcessingQueue(batch, env);
  },
} satisfies ExportedHandler<CloudflareEnv, ProcessingJobMessage>;
